### ISSUE TITLE
Edits to bl-tint2zen, bl-tint2-session etc

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-utilities#13]
@2ion @johnraff 
Hopefully the commit messages are comprehensive enough:

Added bl-tint2restart to restart tint2s from the pipemenu;
Various bugfixes and improvements to getting/killing tint2 processes;
Remove --autostart command arg, so tint2s now killed and restarted anyway;
Made bl-tint2edit and bl-conkyedit executable (previously overlooked)

**Comment by johnraff** [comment]
Thank you.
