### ISSUE TITLE
bl-hotcorners rewrite

### ISSUE THREAD

**Issue by Hjdskes** [BunsenLabs/bunsen-utilities#19]
I enjoyed rewriting bl-aerosnap and contributing to BunsenLabs so much that I also took a look at the other python scripts. Whilst I'm waiting for feedback on my bl-aerosnap rewrite, I'm now working on bl-hotcorners. You can find it in the [rewrite-hotcorners](https://github.com/Unia/bunsen-utilities/tree/rewrite-hotcorners) branch of my fork.

bl-hotcorners is supposed to run as a daemon. The current code, however, does not implement proper daemon behaviour. After a bit of searching, I came acros [python-daemon](https://pypi.python.org/pypi/python-daemon/) which does all the tricky work for you. I'm wondering if I can make bl-hotcorners depend on that. The package is [available](https://packages.debian.org/jessie/python-daemon) in Jessie.

Otherwise, I can copy [this](http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/) code, which also does a lot of the heavy lifting.

**Comment by hhhorb** [comment]
> I enjoyed rewriting bl-aerosnap and contributing to BunsenLabs so much that I also...

To quote Roy Batty in Blade Runner, "THAT'S THE SPIRIT!!!!"

:grinning:

**Comment by johnraff** [comment]
^ YAY!
@Unia I'd say use the python-daemon package, rather than copy in the code. Maybe in the future someone else might want to use it. We can make the package a dependency (or possibly recommend, since it would only be for bl-hotcorners) of bunsen-utilities.

**Comment by hhhorb** [comment]
Recommend, please. I'm sure the daemon is light on RAM, but these things have a cumulative effect.

**Comment by johnraff** [comment]
@Unia can the user control whether the bl-hotcorners daemon runs or not? Would it be an entry in openbox/autostart? 

If so, then @hhhorb having the python-daemon _package_ installed would have no effect on RAM usage unless the user was running the bl-hotcorners daemon. We could have it commented-out of _autostart_ by default.

---

If I understand it correctly, python-daemon is just a library that python script writers can use. It doesn't run any daemons on it's own. Right Jente?

**Comment by Hjdskes** [comment]
Yes the user will be able to control it. Something along the lines of `bl-hotcorners --start` and `bl-hotcorners --kill` or `--stop`.

Using python-daemon will require the package to be installed (so it can not be a recommend), but it is just a module (library) for bl-hotcorners (and other python scripts) to use. It is not a daemon in itself and thus has no effect on RAM usage. (Which I'll measure once I have something working)

**Comment by johnraff** [comment]
@Unia where are we now with this? 

And, is the current GitHub bl-aerosnap your rewritten version? I can't see any traces of commits by you.

**Comment by johnraff** [comment]
@Unia where are we now with this? 

And, is the current GitHub bl-aerosnap your rewritten version? I can't see any traces of commits by you.

**Comment by Hjdskes** [comment]
My (still unfinished) code can be found in my fork: https://github.com/Unia/bunsen-utilities/tree/rewrite-hotcorners

However, I haven't worked on it for several months now.

**Comment by johnraff** [comment]
OK, so we'll stay with the existing code for the time being.
I tried it yesterday and agree that it doesn't behave as a daemon should, so look forward to your new version!

**Comment by Hjdskes** [comment]
I have rebased my changes on top of the current `master` branch and will probably start working on this again the coming few days.

**Comment by johnraff** [comment]
For lack of interest, bl-hotcorners has been removed from bunsen-utilities.
