### ISSUE TITLE
Useless dependency on lightdm?

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-utilities#20]
I do not know how most of these scripts work, but the utility of depending on lightdm is not very obvious...

**Comment by johnraff** [comment]
Ah thank you. It's a legacy from bl-user-setup. That script is now in **bunsen-configs**, which should depend on, or at least recommend, lightdm.

References to bl-user-setup and cb-slim also need removing from README, and bl-kb and bl-tint2restart adding.

I'll do it tomorrow.

**Comment by johnraff** [comment]
Done in **bunsen-utilities (8.2-2)**.
