### ISSUE TITLE
bl-exit: remove call to bl-lock with suspend?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-utilities#27]
**bl-exit**

See this forum post:
https://forums.bunsenlabs.org/viewtopic.php?pid=14909#p14909

Is the call to bl-lock that comes with the suspend action on line 109 superfluous?
Could it be the cause of some of the blackscreen issues people have been getting?

**Comment by ghost** [comment]
Suspend != lock screen. For example, if you are using xscreensaver and set it to lock the screen after N minutes, suspend, and wake up before the N-minute interval has passed, the screen is unlocked. Of course if the locker is called twice for whatever reason, that could be a problem.

**Comment by johnraff** [comment]
That poster reported that the screen was locked automatically by light-locker when going into suspend. 

Of course that's a separate function - in fact xfce4-power-manager has an option "Lock screen when system is going for sleep", so is presumably talking directly to light-locker in that case.

So additionally activating bl-lock from _suspend_ in bl-exit is something to remove, right?

**Comment by ghost** [comment]
If that's the case, I'd say yes.

**Comment by ghost** [comment]
I'd say yes if that's the case.
