### ISSUE TITLE
Remove package scrot and bunsen-utilities is removed with it.

### ISSUE THREAD

**Issue by xaosfiftytwo** [BunsenLabs/bunsen-utilities#29]
Also true for the RC2 image provided by has.

**Comment by hhhorb** [comment]
Good catch! I haven't looked into this yet, why would bunsen-utilities be a dependency of scrot? It should be the other way around.

**Comment by johnraff** [comment]
> It should be the other way around.

It _is_ the other way round.
See:  https://github.com/2ion/bunsen-org/issues/114#issuecomment-173791566
