### ISSUE TITLE
bl-lock

### ISSUE THREAD

**Issue by xaosfiftytwo** [BunsenLabs/bunsen-utilities#40]
Just noticed that 

   bl-lock --help

from the command line locks the screen, where I expected usage notes to see with which arguments it can be run.

**Comment by johnraff** [comment]
In fact, of the scripts in bunsen-utilities, only bl-exit, bl-aerosnap, bl-package-versions and bl-github-upgrade offer any help options.

In the case of bl-lock there are no command line arguments at all. That is the case with most of the other scripts in fact.

If you have the time, then -h|--help options would of course be a welcome addition.

**Comment by johnraff** [comment]
All scripts in **bunsen-utilities** have now been checked for -h|--help options, and they have been added if necessary.

Original authors - @capn-damo and @xaosfiftytwo mainly - please feel free to edit the $HELP strings as you see fit.

I have also removed the unnecessary executability from those files - debhelper will add it at build time.
