### ISSUE TITLE
Commits in master should be in deuterium.

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-utilities#49]
@xaosfiftytwo There have been five commits to the master branch on July 12~14th. These appear to be the same as the recent PR against deuterium. 
Anyway, these commits should not be in master. Can we reverse them?

**Comment by xaosfiftytwo** [comment]
Ah, must have done something wrong.
Sorry about that.
Yes, they can be reversed.

**Comment by johnraff** [comment]
> Yes, they can be reversed.

Would you like to do that?

**Comment by xaosfiftytwo** [comment]
Done.

You are too nice, John.
You could have said: 'Clean up your own mess'

**Comment by johnraff** [comment]
Thank you!

**Comment by hhhorb** [comment]
Lol! The Good Doctor.
