### ISSUE TITLE
yad scripts (deuterium) don't display help text if run in terminal

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-utilities#51]
`bl-obthemes, bl-conkypin` etc. Help text is not showing if run with command

```
<bl-scriptname>  -h|--help
```

**Comment by ghost** [comment]
Seems this snuck in with 53166dd90b15ca5ae4bfabac40b1c2604da1d731.

**Comment by capn-damo** [comment]
...but the executable bit is a different issue.

**Comment by ghost** [comment]
Hehe. Oh.

**Comment by johnraff** [comment]
It's not an issue, in fact. See here: https://github.com/BunsenLabs/bunsen-utilities/issues/52#issuecomment-240308345
