### ISSUE TITLE
bin scripts (deuterium) not executable

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-utilities#52]
Shouldn't these be `chmod +x`?

**Comment by johnraff** [comment]
It's not necessary that the files in the source are executable. I removed the executability bit to make them easier to edit. dh_fixperms will make them executable at build time.

(You can run them with `bash filepath` for testing.)

**man dh_fixperms:**

> ...It makes all files in the standard bin and sbin directories, usr/games/ and etc/init.d executable (since v4).

**Comment by johnraff** [comment]
Executability removed in 001856b

**Comment by johnraff** [comment]
Also, this was mentioned here: https://github.com/BunsenLabs/bunsen-utilities/issues/40#issuecomment-239378921
