### ISSUE TITLE
bl-obthemes: firefox-esr icon lost when restoring

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-utilities#53]
When restoring a saved configuration, the firefox-esr icon in the tint2 panel appears as a generic icon.

Could this be due to `function reloadGTK` no longer working properly with the new firefox?

**Comment by ghost** [comment]
Firefox 45 (current ESR) should still have gtk3 disabled. Could you confirm this on DEbian by looking at the Configure arguments section in about:buildflags? Mine says --enable-default-toolkit=cairo-gtk2 on 45.

**Comment by xaosfiftytwo** [comment]
@2ion,

> Configure arguments
> 
> --enable-application=browser --with-app-name=firefox-esr --enable-release --prefix=/usr --enable-default-toolkit=cairo-gtk2 --with-system-zlib --with-system-bz2 --disable-gconf --enable-readline --enable-system-hunspell --disable-crashreporter --disable-strip --disable-install-strip --enable-startup-notification --enable-system-ffi --with-system-libevent --enable-gstreamer=1.0 --disable-updater --enable-pie --disable-eme --target=x86_64-linux-gnu --host=x86_64-linux-gnu --build=x86_64-linux-gnu --prefix=/usr --with-default-mozilla-five-home=/usr/lib/firefox-esr --enable-official-branding

@capn-damo 
Strange  thing.
Blob restore of a config indeed causes general icon to show for firefox in tint2.
However, restarting firefox-esr restores the firefox specific icon in tint2.
I have no explanation for  this behaviour yet.

**Comment by xaosfiftytwo** [comment]
The problem is this:
When tint2 is started after firefox-esr is already running, tint2 shows the generic icon.Stop and restart firefox and tint2 shows the firefox icon.

**Comment by capn-damo** [comment]
^  Yes. I've just seen this post on the BL forum: https://forums.bunsenlabs.org/viewtopic.php?pid=35244#p35244

It is a tint2 issue, not bl-obthemes

**Comment by o9000** [comment]
It would be great if someone could try https://gitlab.com/o9000/tint2/commit/008eebe4b1238c827e76b8c77aee1231f61a748f and let me know if it fixes the issue. Otherwise we should see what I have to do to replicate your setup somehow to reproduce the problem myself.

**Comment by o9000** [comment]
Thanks to xaos's instructions, I reproduced the issue.

This is not a tint2 bug. You may see that the Alt-Tab switcher of Openbox also shows the default icon for Firefox, just as xprop. The window bar of Firefox also shows the default icon.

**Comment by xaosfiftytwo** [comment]
@damo,
We may have to resort to a workaround in bl-obthemes:
See [https://forums.bunsenlabs.org/viewtopic.php?pid=35334#p35334](url)

**Comment by damo** [comment]
@xaosfiftytwo, please do not use "@damo" to refer to capn-damo. You are subscribing me to all subsequent comments on the issue and spamming my inbox until I unsubcribe. Thank you.

**Comment by xaosfiftytwo** [comment]
@capn-damo ,
Sorry about that. Will be more careful in future.
