### ISSUE TITLE
bl-exitrc [style] dir requires full filepath

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-utilities#55]
```
[style]
dir = ~/filepath or $HOME/filepath
```

This isn't sufficient - the full filepath is necessary.

**Comment by ghost** [comment]
https://github.com/BunsenLabs/bunsen-utilities/blob/deuterium/bl-exitrc#L74 is pretty clear what is intended, though the code doesn't implement what is promised @ https://github.com/BunsenLabs/bunsen-utilities/blob/deuterium/bin/bl-exit#L188.

**Comment by johnraff** [comment]
So, fix the code, or fix the comment?
( @xaosfiftytwo is on sabbatical atm.)

**Comment by ghost** [comment]
I can't find the offending section @capn-damo quoted in the OP anymore.
