### ISSUE TITLE
bl-reload-gtk23 error message when reloading running xsettingsd

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-utilities#69]
**bl-reload-gtk23: function sync_gtk3():**
If xsettingsd is already running, the HUP signal is correctly sent, but the script returns with an error message:
`WARNING bl-reload-gtk23 main() : Failed to reload GTK3 settings: 'int' object is not callable`
The utility returns `2` but otherwise seems to work as expected.
If xsettingsd is not yet running, and needs starting, no error is thrown.

Inspection of the code suggested this line:
https://github.com/BunsenLabs/bunsen-utilities/blob/68cef06a7b69290b85cf0afada7af3376c82100a/bin/bl-reload-gtk23#L133
If edited to:
`        logging.debug("Found xsettingsd process and sent SIGHUP: PID %d", proc.pid())` 
(by analogy with line 139) then the issue appears to be fixed. 
However, this was a purely empirical fix and needs attention from the developer.

**Comment by ghost** [comment]
Yes this is a bug. Accidentally also the code path I did not really test (= create xsettingsd config and test). Your fix is correct; will create a PR based on that.

**Comment by ghost** [comment]
Thanks!
